// src/app/news/news.component.ts
import { Component, OnInit } from '@angular/core';
import {Subscription} from "rxjs";
import {formatDate} from "../date";
import {News} from "../model/news";
import {NewsService} from "../news.service";

@Component({
  selector: 'app-news',
  templateUrl: './news.component.html',
  styleUrls: ['./news.component.css']
})
export class NewsComponent implements OnInit {
  public news: News;
  public days: string[];
  private sub: Subscription;

  constructor(private newsService: NewsService) { }

  ngOnInit(): void {
    this.sub = this.newsService.get().subscribe((news: News) => {
      this.news = news;
      this.days = Object.keys(news).sort().reverse()
    })
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe()
  }

  buildTitle(isoDate: string): string {
    const MS_IN_A_DAY = 1000 * 60 * 60 * 24;
    let date = new Date(isoDate);
    let today = new Date();
    let diffInMs = today.getTime() - date.getTime();
    let diffInDays = Math.floor(diffInMs / MS_IN_A_DAY);

    switch (diffInDays) {
      case 0:
        return 'Heute gefunden';
      case 1:
        return 'Gestern gefunden';
      default:
        return `Vor ${diffInDays} Tagen gefunden`;
    }
  }

  formatDate = formatDate
}

<ul>
  <li *ngFor="let day of days; let i = index">
    <h2 class="day">{{ i == 0 ? 'Gestern' : 'Vor ' + (i + 1) + ' Tagen'}} gefunden</h2>
    <ul>
      <li *ngFor="let event of news[day]">
        <span class="badge badge-info">{{formatDate(event.datetime)}}</span>
        <a href="{{event.url}}">{{event.title}}</a> im <a href="{{event.venue.URL}}">{{event.venue.Name}}</a>
      </li>
    </ul>
  </li>
</ul>

// src/components/news.tsx
import * as React from 'react'
import {Event} from "../model/event"
import {News} from "../model/news"
import {Observable, Subscription} from "rxjs"
import {ajax} from "rxjs/ajax"
import {pluck} from "rxjs/operators"
import {Agenda} from "../model/agenda"

export const NewsComponent = () => {
    let news$: Observable<Agenda> = ajax('/rest/news').pipe(pluck('response'))

    return (
        <div>
            <h2 className={'hidden'}>News</h2>
            <NewsList news$={news$}/>
        </div>
    )
}

const EventComponent = ({event}: { event: Event }) => {
    return (
        <li>
            <a href={event.venue.URL}
               className={'venue-badge'}>{event.venue.Name}</a>
            &nbsp;
            <a href={event.url}>{event.title}</a>
        </li>
    )
}

const DayComponent = ({day, events}: { day: string, events: Event[] }) => {
    return (
        <li>
            <h3>{ buildTitle(day) }</h3>
            <ul>
                {events.map((event: Event) => <EventComponent key={event.url} event={event}/>)}
            </ul>
        </li>
    )
}


function buildTitle(isoDate: string): string {
    const MS_IN_A_DAY = 1000 * 60 * 60 * 24;
    let date = new Date(isoDate);
    let today = new Date();
    let diffInMs = today.getTime() - date.getTime();
    let diffInDays = Math.floor(diffInMs / MS_IN_A_DAY);

    switch (diffInDays) {
        case 0:
            return 'Heute gefunden';
        case 1:
            return 'Gestern gefunden';
        default:
            return `Vor ${diffInDays} Tagen gefunden`;
    }
}

interface NewsListState {
    news: News
    days: string[]
    sub: Subscription
}

interface NewsListProps {
    news$: Observable<News>
}

export class NewsList extends React.Component<NewsListProps, NewsListState> {
    constructor(props: NewsListProps) {
        super(props)
        this.state = {news: {}, days: [], sub: null}
    }

    componentDidMount() {
        let sub = this.props.news$.subscribe((news: News) => {
            let days = Object.keys(news).sort().reverse()
            this.setState({news, days, sub})
        })
    }

    componentWillUnmount() {
        this.state.sub.unsubscribe()
        this.setState({sub: null})
    }

    render() {
        return (
            <ul>
                {this.state.days.map((day: string) => {
                    let events = this.state.news[day]
                    return <DayComponent key={day} day={day} events={events}/>
                })}
            </ul>
        )
    }
}
